#!/usr/bin/env python3
import os
import sys
import ast
import subprocess
import re

class DocWriter:
    """Simulates the doc-writer agent.
    Statically analyzes a Python file to auto-generate structured Markdown API documentation.
    """
    def __init__(self, filepath):
        self.filepath = filepath
        self.filename = os.path.basename(filepath)

    def generate(self):
        print(f"[{self.__class__.__name__}] Analyzing {self.filename}...")
        if not os.path.exists(self.filepath):
            return f"Error: File '{self.filepath}' not found."

        with open(self.filepath, 'r', encoding='utf-8') as f:
            code = f.read()

        try:
            tree = ast.parse(code)
        except SyntaxError as e:
            return f"Syntax Error parsing {self.filename}: {e}"

        doc_content = []
        doc_content.append(f"# API Documentation: `{self.filename}`\n")
        doc_content.append(f"Auto-generated by `doc-writer` agent simulation.\n")

        # Extract module-level docstring
        module_doc = ast.get_docstring(tree)
        if module_doc:
            doc_content.append(f"## Module Overview\n\n{module_doc}\n")

        functions = []
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef):
                # Ignore private functions starting with _ unless they have docstrings
                if node.name.startswith('_') and not ast.get_docstring(node):
                    continue
                functions.append(node)

        if functions:
            doc_content.append("## Function Reference\n")
            for func in sorted(functions, key=lambda x: x.lineno):
                args = [arg.arg for arg in func.args.args]
                # Handle default values representation simply
                defaults = [ast.unparse(d) if hasattr(ast, 'unparse') else 'None' for d in func.args.defaults]
                arg_strs = []
                # Align defaults with arguments from the right
                diff = len(args) - len(defaults)
                for i, arg in enumerate(args):
                    if i >= diff:
                        arg_strs.append(f"{arg}={defaults[i - diff]}")
                    else:
                        arg_strs.append(arg)
                
                sig = f"{func.name}({', '.join(arg_strs)})"
                doc_content.append(f"### `def {sig}`\n")
                doc_content.append(f"- **Line Number**: {func.lineno}")
                
                docstring = ast.get_docstring(func)
                if docstring:
                    doc_content.append(f"- **Description**:\n  ```text\n  {docstring}\n  ```\n")
                else:
                    doc_content.append(f"- **Description**: *No docstring provided.*\n")
                doc_content.append("")

        output_name = self.filename.replace('.py', '_docs.md')
        output_path = os.path.join(os.path.dirname(self.filepath), output_name)
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(doc_content))
            
        print(f"[{self.__class__.__name__}] Generated documentation: {output_path}")
        return output_path


class CodeReviewer:
    """Simulates the code-reviewer agent.
    Performs static checks for security, style, and code quality, generating a Markdown review report.
    """
    def __init__(self, filepath):
        self.filepath = filepath
        self.filename = os.path.basename(filepath)

    def review(self):
        print(f"[{self.__class__.__name__}] Reviewing {self.filename}...")
        if not os.path.exists(self.filepath):
            return f"Error: File '{self.filepath}' not found."

        with open(self.filepath, 'r', encoding='utf-8') as f:
            lines = f.readlines()
            code = "".join(lines)

        findings = {
            "critical": [],
            "readability": [],
            "performance": [],
            "positive": []
        }

        # Statically check AST
        try:
            tree = ast.parse(code)
        except SyntaxError as e:
            return f"Syntax Error: {e}"

        # 1. Check functions for missing docstrings & global usage
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef):
                if not ast.get_docstring(node) and not node.name.startswith('_'):
                    findings["readability"].append({
                        "line": node.lineno,
                        "item": f"Function `{node.name}` is missing a docstring.",
                        "fix": "Add a descriptive docstring explaining arguments, return values, and behavior."
                    })
                
                # Check for 'global' statements
                for subnode in ast.walk(node):
                    if isinstance(subnode, ast.Global):
                        findings["critical"].append({
                            "line": subnode.lineno,
                            "item": f"Global statement used inside `{node.name}` for global variables: {', '.join(subnode.names)}.",
                            "fix": "Avoid global state. Pass variables as arguments or use class encapsulation."
                        })

        # 2. Check for resource safety (open without 'with')
        open_without_with_lines = []
        for i, line in enumerate(lines, 1):
            if "open(" in line and "with " not in line:
                # Check if it's a comment or a close statement
                if not line.strip().startswith("#"):
                    open_without_with_lines.append(i)
        
        for lineno in open_without_with_lines:
            findings["critical"].append({
                "line": lineno,
                "item": "File opened using direct `open()` without a `with` statement.",
                "fix": "Use a context manager `with open(...) as f:` to ensure the file descriptor is closed reliably even if exceptions occur."
            })

        # 3. Check for hardcoded external HTTP endpoints
        for i, line in enumerate(lines, 1):
            if "http://" in line or "https://" in line:
                if "api.example.com" in line:
                    findings["critical"].append({
                        "line": i,
                        "item": f"Hardcoded test API URL found: `{line.strip()}`.",
                        "fix": "Extract API endpoints to environmental configurations or settings variables."
                    })

        # Positive comments
        if len(findings["critical"]) == 0:
            findings["positive"].append("Excellent error boundaries and security hygiene observed in this check.")
        else:
            findings["positive"].append("Modular structure handles logic separation well.")

        # Generate Review Report
        report = []
        report.append(f"# Code Review Report: `{self.filename}`\n")
        report.append("Generated by the automated `code-reviewer` simulation.\n")
        
        report.append("## 📋 Summary")
        total_issues = len(findings["critical"]) + len(findings["readability"])
        report.append(f"Review completed. Found **{len(findings['critical'])}** critical issue(s) and **{len(findings['readability'])}** readability suggestion(s).\n")

        report.append("## 🔴 Critical Issues (Bugs / Security / Best Practices)")
        if findings["critical"]:
            for issue in findings["critical"]:
                report.append(f"- **Line {issue['line']}**: {issue['item']}")
                report.append(f"  * **Recommendation**: {issue['fix']}\n")
        else:
            report.append("*None identified.*\n")

        report.append("## 🟡 Readability Improvements")
        if findings["readability"]:
            for issue in findings["readability"]:
                report.append(f"- **Line {issue['line']}**: {issue['item']}")
                report.append(f"  * **Recommendation**: {issue['fix']}\n")
        else:
            report.append("*None identified.*\n")

        report.append("## ✅ Positive Observations")
        for pos in findings["positive"]:
            report.append(f"- {pos}")
        report.append("")

        output_name = self.filename.replace('.py', '_review_report.md')
        output_path = os.path.join(os.path.dirname(self.filepath), output_name)
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(report))

        print(f"[{self.__class__.__name__}] Generated code review report: {output_path}")
        return output_path


class TestRunner:
    """Simulates the test-runner agent.
    Runs unit tests (via pytest) and captures outputs to create a Markdown test report.
    """
    def __init__(self, test_filepath):
        self.test_filepath = test_filepath
        self.test_filename = os.path.basename(test_filepath)

    def run_tests(self):
        print(f"[{self.__class__.__name__}] Executing tests in {self.test_filename}...")
        if not os.path.exists(self.test_filepath):
            return f"Error: Test file '{self.test_filepath}' not found."

        # Execute pytest command
        cmd = ["python3", "-m", "pytest", "-v", self.test_filepath]
        result = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

        stdout = result.stdout
        exit_code = result.returncode

        # Parse output for statistics
        passed = len(re.findall(r"PASSED", stdout))
        failed = len(re.findall(r"FAILED", stdout))
        
        status = "🟢 PASS" if exit_code == 0 else "🔴 FAIL"

        report = []
        report.append(f"# Test Execution Report: `{self.test_filename}`\n")
        report.append("Generated by the automated `test-runner` simulation.\n")
        
        report.append("## 📊 Execution Summary")
        report.append(f"- **Overall Status**: {status}")
        report.append(f"- **Exit Code**: {exit_code}")
        report.append(f"- **Passed Tests**: {passed}")
        report.append(f"- **Failed Tests**: {failed}")
        report.append("")

        report.append("## 📝 Console Output")
        report.append("```text")
        report.append(stdout)
        report.append("```\n")

        output_name = self.test_filename.replace('.py', '_test_report.md')
        output_path = os.path.join(os.path.dirname(self.test_filepath), output_name)
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(report))

        print(f"[{self.__class__.__name__}] Generated test report: {output_path}")
        return output_path


def main():
    print("==================================================")
    print("🚀 AUTOMATED AGENT PIPELINE RUNNER STARTED")
    print("==================================================\n")

    target_file = "sample.py"
    test_file = "test_calculator.py"

    # Step 1: DocWriter
    writer = DocWriter(target_file)
    doc_path = writer.generate()
    print("-" * 50)

    # Step 2: CodeReviewer
    reviewer = CodeReviewer(target_file)
    review_path = reviewer.review()
    print("-" * 50)

    # Step 3: TestRunner
    runner = TestRunner(test_file)
    test_path = runner.run_tests()
    
    print("\n==================================================")
    print("🎉 PIPELINE COMPLETED SUCCESSFULLY!")
    print(f"- Documentation: {os.path.abspath(doc_path)}")
    print(f"- Code Review:   {os.path.abspath(review_path)}")
    print(f"- Test Report:   {os.path.abspath(test_path)}")
    print("==================================================")

if __name__ == "__main__":
    main()
